config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :drafts
  get 'markdown/preview'
  get 'items', controller: :home, action: :items
  get 'feeds', controller: :home, action: :feeds

  resources :users, only: [ :show ], path: '', controller: :profile do
    resources :items, only: [ :index, :show ] do
      resource :stock, only: [ :create, :destroy ]
      resource :comment, only: [ :create, :update, :destroy ]
    end
    resources :stocks, only: [ :index ]
    resources :comments, only: [ :index ]
  end

end

app/models/concerns/find_by_name.rb
module FindByName extend ActiveSupport::Concern

  module ClassMethods
    def find_by_param(id)
      self.find_by_name!(id)
    end
  end

  def to_param
    self.name
  end
end

app/models/following_tag.rb
class FollowingTag < ActiveRecord::Base
  belongs_to :user
  belongs_to :tag, class_name: ActsAsTaggableOn::Tag

  validates_presence_of :user_id, :tag_id
  validates_uniqueness_of :user_id, scope: :tag_id

  def items
    Item.tagged_with(self.tag.name)
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :stocks

  acts_as_taggable

  validates_presence_of :title, :user_id

  scope :recent, -> { order(updated_at: :desc) }
  scope :drafts, -> { where(published_at: nil) }
  scope :published, -> { where.not(published_at: nil) }

  def publish
    self.published_at ||= Time.current
  end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates_uniqueness_of :follower_id, scope: :followed_id
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :item
  belongs_to :user

  validates_uniqueness_of :item_id, scope: :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
  has_many :stocks, dependent: :destroy
  has_many :stock_items, through: :stocks, source: :item

  has_many :active_relationships, class_name: "Relationship",
           foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship",
           foreign_key: "followed_id", dependent: :destroy
  has_many :follower, through: :passive_relationships

  has_many :following_tags, dependent: :destroy

  validates_presence_of :name

  def stock(item)
    stocks.create(item: item)
  end

  def unstock(item)
    stocks.find_by!(item: item).destroy
  end

  def stocked?(item)
    stocks.find_by(item: item).present?
  end

  def follow_user(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow_user(other_user)
    active_relationships.find_by!(followed_id: other_user.id).destroy
  end

  def follow_tag(tag)
    following_tags.create(tag_id: tag.id)
  end

  def unfollow_tag(tag)
    following_tags.find_by!(tag_id: tag.id).destroy
  end

  def contribution
    items.inject(0){ |sum, item| sum + item.stocks.count }
  end

  include FindByName
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  before_action :set_draft_item, only: [ :show, :edit, :update, :destroy ]

  def index
    @current_id ||= params[:current_id]
    @drafts = current_user.items.drafts
  end

  def new
    @url = drafts_path
    @draft = current_user.items.new
  end

  def edit
    @url = draft_path(@draft)
  end

  def show
    respond_to do |format|
      format.js
    end
  end

  def create
    @draft = current_user.items.new(draft_item_params)
    msg = '下書きを保存しました。'
    if params[:publish]
      @draft.publish
      msg = '記事を公開しました。'
    end
    if @draft.save
      redirect_to drafts_path(current_id: @draft.id), notice: msg
    else
      @url = drafts_path
      render :new, alert: '下書きが保存できませんでした。'
    end
  end

  def update
    msg = '下書きを更新しました。'
    if params[:publish]
      @draft.publish
      msg = '記事を公開しました。'
    end
    if @draft.update(draft_item_params)
      redirect_to drafts_path(current_id: @draft.id), notice: msg
    else
      @url = draft_path(@draft)
      render :edit, alert: '下書きが更新できませんでした。'
    end
  end

  def destroy
    @draft.destroy
    redirect_to drafts_path, notice: '下書きを削除しました。'
  end

  private

    def set_draft_item
      @draft = current_user.items.drafts.find(params[:id])
    end
  
    def draft_item_params
      params.require(:item).permit([ :title, :content, :tag_list ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @active_tab = params[:active_tab] || :all
  end

  def items
    @items = Item.published.recent.page params[:page]
    respond_to do |format|
      format.js
    end
  end

  def feeds
    # FIXME
    @items = Item.published.recent.page params[:page]
    respond_to do |format|
      format.js { render :items }
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_user
  before_action :set_item, only: [ :show ]

  def index
    @items = @user.items.published.recent.page params[:page]
    respond_to do |format|
      format.html
      format.json { render json: @items }
      format.js
    end
  end

  private

    def set_user
      @user = User.find_by_param(params[:user_id])
    end

    def set_item
      @item = Item.find(params[:id])
    end
end

app/controllers/markdown_controller.rb
class MarkdownController < ApplicationController
  def preview
    @text = params[:text]
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
    @active_tab = params[:active_tab] || :recent
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_user
  before_action :set_item, only: [ :create, :destroy ]

  def index
    @stocks = @user.stock_items
    respond_to do |format|
      format.js
    end
  end

  def create
    current_user.stock(@item)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    current_user.unstock(@item)
    respond_to do |format|
      format.js
    end
  end

  private

    def set_user
      @user = User.find_by_param(params[:user_id])
    end

    def set_item
      @item = Item.published.find(params[:item_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    text ||= ""
    options = {
        filter_html: true,
        hard_wrap: true,
        link_attributes: { rel: 'nofollow', target: '_blank' },
        space_after_headers: true,
        fenced_code_blocks: true
    }

    extensions = {
        autolink: true,
        superscript: true,
        disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/views/drafts/_draft.html.haml
= link_to draft_path(draft), class: "draft_item", id: "draft_item_#{draft.id}", remote: true do
  .list-group-item
    %h4= draft.title
    = draft.updated_at

app/views/drafts/_form.html.haml
.col-sm-12
  = simple_form_for @draft, url: @url do |f|
    = f.input :title, placeholder: 'タイトル', label: false, autofocus: true
    .form-group
      = text_field_tag 'item[tag_list]', @draft.tag_list.join(','), { class: "form-control", data: { role: "tagsinput" } }
    .row.col-sm-12
      = f.input :content, placeholder: '本文', label: false, input_html: { rows: 20 }, wrapper_html: { class: "col-sm-6" }
      #markdown-preview.preview-content.col-sm-6
        = markdown(@draft.content)
    .row.col-sm-12
      = f.button :submit, class: "btn btn-success"
      = f.button :submit, '公開する', name: 'publish', class: "btn btn-primary pull-right"

app/views/drafts/_show.html.haml
#draft-show-header
  .draft-commands
    = link_to '編集する', edit_draft_path(@draft), class: "btn btn-default"
    = link_to draft_path(@draft), class: "btn btn-danger pull-right", method: :delete do
      %i.glyphicon.glyphicon-trash
      %span 削除する

  .draft-body
    .draft-title
      .draft-header= @draft.title
      .draft-tags
        - @draft.tag_list.each do |tag|
          .tag.label.label-info= tag
    .draft-content
      = markdown(@draft.content)

app/views/drafts/edit.html.haml
= render 'form'

app/views/drafts/index.html.haml
#draftsSidebar.col-sm-3
  .panel.panel-default
    .panel-heading
      .row
        %h4.col-sm-9 下書き一覧
        = link_to new_draft_path, class: "btn btn-success" do
          %i.glyphicon.glyphicon-pencil
    .list-groups
      = render partial: 'draft', collection: @drafts

#draftsPreview.col-sm-9


= hidden_field_tag "current_id", @current_id

app/views/drafts/new.html.haml
= render 'form'

app/views/drafts/show.js.erb
$('#draftsPreview').html("<%= j(render 'show') %>");

app/views/home/_item.html.haml
%tr
  %td
    .item-note
      = link_to item.user.name, item.user
      %span.date= " が#{item.created_at}に投稿"
    .title= link_to item.title, [ item.user, item ]

app/views/home/index.html.haml
.col-sm-12
  - if user_signed_in?
    %h1 プログラミング知識を共有しよう。

    = link_to 'ノウハウ・Tipsを投稿する', new_draft_path, class: "btn btn-success"

    .row.col-sm-12
      .col-sm-8
        = render 'shared/home_tabs'
        .tab-content
          %table.table
            %tbody#tab_main

    = hidden_field_tag "active_tab", @active_tab

  - else
    .col-sm-6
      .well.well-lg
        Copy Qiita 2
    .col-sm-6
      %h1 サインアップ

app/views/home/items.js.erb
$('#tab_main').html("<%= j(render @items)%>");

app/views/items/index.html.haml
%h2 最近の投稿

%table.table
  = render @items

  = paginate @items

app/views/items/index.js.erb
$('#tab_main').html("<%= j(render @items)%>");

app/views/items/show.html.haml
.item_header
  .col-sm-9
    .item_header__title= @item.title
    .item_header__tags= @item.tag_list
    %ul.item_header__info.list-unstyled.list-inline
      %li= "#{@item.user.name}が"
      %li= "#{@item.created_at} に投稿"

  #js-stock-updating-area.col-sm-3
    = render 'stocks/header_stock_info'

.row
  .col-sm-9
    .main_content= markdown(@item.content)
  .col-sm-3
    #user-side-info
      .user__name= @item.user.name
      .user__contribution="#{@item.user.contribution} Contribution"

app/views/layouts/_header.html.haml
.row
  .navbar.navbar-default
    .navbar-header
      = link_to 'CopyQiita2', root_path, class: "navbar-brand"

    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        %li{style: "margin-top:8px;"}
          .btn-group
            %button#dropdownMenuPost.btn.btn-success.dropdown-toggle{ type: "button", data: { toggle: "dropdown"}, area: { haspopup: "true", expanded: "false" }}
              %i.glyphicon.glyphicon-pencil
              %span 投稿する
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to drafts_path do
                  %i.glyphicon.glyphicon-list
                  %span 下書き一覧
              %li
                = link_to new_draft_path do
                  %i.glyphicon.glyphicon-pencil
                  %span 下書きを書く

        %li.dropdown
          = link_to '#"', class: "dropdown-toggle", data: { toggle: "dropdown" }, role: "button", area: { haspopup: "true", expanded: "false" } do
            %span= current_user.email
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to user_path(current_user) do
                %i.glyphicon.glyphicon-user
                %span マイページ
            %li
              = link_to edit_user_registration_path do
                %i.glyphicon.glyphicon-cog
                %span 設定
            %li
              = link_to destroy_user_session_path, method: :delete do
                %i.glyphicon.glyphicon-log-out
                %span ログアウト
      - else
        %li= link_to 'ログイン', new_user_session_path

app/views/layouts/_message.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{ class: "alert alert-#{name == "notice" ? "success" : "danger" }"}
      %button.close{ area: { hidden: "true" }, data: { dismiss: "alert" }, type: "button" } &times;
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CopyQiita
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container-fluid
      = render 'layouts/header'

      .col-sm-12
        = render 'layouts/message'
      .row
        = yield

app/views/markdown/preview.js.erb
$('#markdown-preview').html("<%= j(markdown(@text)) %>")

app/views/shared/_home_tabs.html.haml
%ul.nav.nav-tabs
  %li.js-my-page-tab{ role: "presentation" }
    = link_to 'フィード', feeds_path, remote: true, id: "my-page-tab_feeds"
  %li.js-my-page-tab.active{ role: "presentation" }
    = link_to '全ての投稿', items_path, remote: true, id: "my-page-tab_all"

app/views/shared/_tab_menus.html.haml
%ul.nav.nav-tabs
  %li.js-my-page-tab.active{ role: "presentation" }
    = link_to '最近の投稿', user_items_path(current_user), remote: true, id: "my-page-tab_recent"
  %li.js-my-page-tab{ role: "presentation" }
    = link_to 'ストックした投稿', user_stocks_path(current_user), remote: true, id: "my-page-tab_stocks"
  %li.js-my-page-tab{ role: "presentation" }
    = link_to 'コメント', user_comments_path(current_user), remote: true, id: "my-page-tab_comments"

app/views/stocks/_header_stock_info.html.haml
%ul.list-inline.row
  %li.col-sm-6.item_header__summary.separator
    .item_header__summary_count
      %span#item_stock_count= "#{@item.stocks.count}"
    .r ストック
  %li.col-sm-6.item_header__summary
    .item_header__summary_count= "#{0}"
    .r コメント

#js-stock-action
  - if current_user.stocked?(@item)
    = link_to user_item_stock_path(@item.user, @item), method: :delete, remote: true, class: "btn btn-block btn-warning" do
      %i.glyphicon.glyphicon-folder-open
      %span ストック解除
  - else
    = link_to user_item_stock_path(@item.user, @item), method: :post, remote: true, class:"btn btn-block btn-default item_header__stock" do
      %i.glyphicon.glyphicon-folder-close
      %span ストック

app/views/stocks/_stock.html.haml
%tr
  %td
    .item-note
      = link_to stock.user.name, stock.user
      %span.date= " が#{stock.created_at}に投稿"
    .title= link_to stock.title, [ stock.user, stock ]

app/views/stocks/create.js.erb
$('#js-stock-updating-area').html("<%= j(render '/stocks/header_stock_info')%>")

app/views/stocks/destroy.js.erb
$('#js-stock-updating-area').html("<%= j(render '/stocks/header_stock_info')%>")

app/views/stocks/index.js.erb
$('#main_content').html("<%= j(render @stocks)%>")